name: Deploy
on:
  push:
    branches:
      - main
permissions: read-all
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm install
        run: npm install

      - name: build
        run: npm run build
