name: Deploy
on:
  push:
    branches:
      - main
permissions: read-all
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install boto3
        run: |
          python -m pip install --upgrade pip
          pip install boto3

      - name: npm install
        run: npm install

      - name: build
        run: npm run build

      - name: Deploy  # S3にデプロイ
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_SECRET }}
        run: |
          python .github/workflows/deploy.py
