name: Deploy
on:
  push:
    branches:
      - main
permissions: read-all
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: npm install
        run: npm install

      - name: build
        run: npm run build
      - name: Deploy  # S3にデプロイ
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_KEY_ID }}
        run: |
          aws s3 sync --region ap-northeast-1 --delete --exact-timestamps public s3://tomoyat.dev